name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9

    - name: 🖱️ LLVM Install
      uses: ZhongRuoyu/setup-llvm@405ac952f13f3ee4d376adc2b7a96e5f48d1f73f
      with:
        llvm-version: 18

    - name: ⚙️ Install Nextest
      uses: taiki-e/install-action@nextest

    - name: ⌛ Packages Tests
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run --profile ci
