name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@5aa646dfb739dff33bfae50a6193d9673a68e344
      with:
        components: "clippy"

    - name: 🖱️ LLVM Install
      uses: ZhongRuoyu/setup-llvm@405ac952f13f3ee4d376adc2b7a96e5f48d1f73f
      with:
        llvm-version: 18

    - name: 🔧 Packages test
      uses: jacderida/cargo-nextest@initial
      with:
        profile: ci
